### ISSUE TITLE
having a problem integrating with wordpress

### ISSUE THREAD

**Issue by SidraBaig** [magic-coding/thawani-pay-woocommerce#14]
While I am trying thawani-pay-woo-commerce integration with WordPress, all files are uploaded at the time of uploading the file, but .PHP files give an error and are not uploaded. Help me out in this regard; what is the reason? How can I solve this issue?

**Comment by malnafei** [comment]
Hi @SidraBaig 
Thanks for reaching us. Cloud you please share more details like error message, code or a screenshot.

**Comment by SidraBaig** [comment]
by clicking on it and starting uploading the file, files start to upload
after 40 to 50% of uploading, an error prompted that file couldn't
![wordpress uploading image](https://user-images.githubusercontent.com/125665257/219672989-18eac27e-14a7-4c22-98af-003df981184f.png)
 be uploaded.
