### ISSUE TITLE
Product name has to be 40 character long

### ISSUE THREAD

**Issue by w7shdev** [magic-coding/thawani-pay-woocommerce#2]
Hello 

This will cause a issue in sending the payload 

https://github.com/magic-coding/thawani-pay-woocommerce/blob/c1164b292f60bf1b3cc461760327c571da2760bd/thawani-pay-woocommerce.php#L206

**Comment by magic-coding** [comment]
Hello @w7shdev
Thank you for reporting this issue.
Try to use `substr($product_name, 0, 40)` to solve this issue.

Thank you.

**Comment by magic-coding** [comment]
Issue fixed, please check [65c61a1](https://github.com/magic-coding/thawani-pay-woocommerce/commit/65c61a157e70215362065db43622df09e10ecdc2)
