### ISSUE TITLE
Get the Taxes price ( VAT ) 

### ISSUE THREAD

**Issue by w7shdev** [magic-coding/thawani-pay-woocommerce#4]
*Description*
Add a configuration for getting the taxes and send it to the payload if the taxes implies. For example sending a VAT to the payload

**Comment by w7shdev** [comment]
I think it's best to not send the VAT in payload because  if __VAT__ is less than 100 Biza then the generation of the session id will fail. 
so it's better to send the product + the tax

**Comment by magic-coding** [comment]
Hi @w7shdev 
Thank you for your suggestion and contribution. WooCommerce Tax feature will be available in coming release.
Right now it's better to add tax with product regular price.
