### ISSUE TITLE
Product Title Shorting system 

### ISSUE THREAD

**Issue by QaisAljedyani** [magic-coding/thawani-pay-woocommerce#5]
I noticed that with the product bundle plugin and long-form product titles, it send an error and cause an issues
recommend a product title convector to be less than 40 charachter, I am having the same issue with my custom-made plugin for thawani.

**Comment by magic-coding** [comment]
Hello @QaisAljedyani .
This issue already fixed [65c61a157e70215362065db43622df09e10ecdc2](https://github.com/magic-coding/thawani-pay-woocommerce/commit/65c61a157e70215362065db43622df09e10ecdc2) .

Please download the latest release from [here](https://github.com/magic-coding/thawani-pay-woocommerce/releases/tag/v1.1)

Thank you

**Comment by QaisAljedyani** [comment]
Well done @magic-coding,
