### ISSUE TITLE
Products Names language issue

### ISSUE THREAD

**Issue by itssomar** [magic-coding/thawani-pay-woocommerce#6]
Dear sir,
Thanks for your plugin but I have an error when I change the name of products to Arabic! I reviced the below error:

{"success":false,"code":4000,"description":"Invalid information","data":{"error":[{"field":"products[0]._name","message":"The Name field is required."}]}}

I hope if you can solve this issue 

Best Regards

**Comment by magic-coding** [comment]
Hello @itssomar 
Please share the Arabic product name with us to use the same product name while we test the plugin.
Thank you.

**Comment by itssomar** [comment]
Hi 
All products in Arabic language ! for example منتج تجريبي 
Please try to change any products name to Arabic and you can see the error.

**Comment by w7shdev** [comment]
any update on this ?

**Comment by magic-coding** [comment]
Hello @itssomar & @w7shdev 
Please download the latest version from here [Download v1.2.0](https://github.com/magic-coding/thawani-pay-woocommerce/releases/download/v1.2.0/thawani-pay-v1.2.0.zip)

This release includes products with Arabic name support.
if you face any other issues please open a new issue.

Thank you.
