### ISSUE TITLE
While redirect thawani payment its gives 404 error

### ISSUE THREAD

**Issue by Shefali1611** [magic-coding/thawani-pay-woocommerce#7]
I have created customer using thawani API(create customer) and passing customer id into checkout session thawani API and fatching session id to redirect payment page but getting 404 error.

I am using this URL
https://uatcheckout.thawani.om/pay/(thawani.data.session_id)?key=(MYPublishKey)

**Comment by magic-coding** [comment]
Hi @Shefali1611 
Please send your case to Thawani support team at support@thawani.om
This repo only for woo-commerce Thawani plugin and the card tokenization feature still not implemented in this plugin.

Thank you
